name: Dependabot auto-merge
on: pull_request_target
permissions:
  pull-requests: write
  contents: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          pull-request-number: ${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
