name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}
  schedule:
    - cron: '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: install dependencies
      run: npm ci
    - name: lint js
      run: npm run lint:js
    - name: lint hbs
      run: npm run lint:hbs
    - name: test
      run: npm run test:ember

  test-floating:
    name: Floating Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: install dependencies
      run: npm install --no-package-lock
    - name: test
      run: npm run test:ember

  try-scenarios:
    name: ember-try

    runs-on: ubuntu-latest

    needs: test

    strategy:
      matrix:
        ember-try-scenario:
         - ember-lts-3.12
         - ember-lts-3.16
         - ember-release
         - ember-beta
         - ember-canary
         - ember-default-with-jquery
         - ember-classic

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: install dependencies
      run: npm ci
    - name: test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
