name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - run: pnpm install --ignore-scripts
      - name: publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
