name: Tag Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Semver Release Type (major,minor,patch)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.MY_TOKEN }}
    - name: Validate releaseType
      run: npx in-string-list ${{ github.event.inputs.releaseType }} major,minor,patch
    - name: Setup Git
      run: |
        git config --global user.name "Jonathan Johnson"
        git config --global user.email "jon.johnson@ucsf.edu"
    - name: Increment Version
      run: npm version ${{ github.event.inputs.releaseType }}
    - name: Push Changes
      run: git push --follow-tags